execute as @a if score @s archer_used matches 3 run advancement grant @s only pvp_data:jobs/archer/3c_archer
execute as @a if score @s archer_used matches 20 run advancement grant @s only pvp_data:jobs/archer/20c_archer
execute as @a if score @s assassin_used matches 3 run advancement grant @s only pvp_data:jobs/assassin/3c_assassin
execute as @a if score @s assassin_used matches 20 run advancement grant @s only pvp_data:jobs/assassin/20c_assassin
execute as @a if score @s bommer_used matches 3 run advancement grant @s only pvp_data:jobs/bommer/3c_bommer
execute as @a if score @s bommer_used matches 20 run advancement grant @s only pvp_data:jobs/bommer/20c_bommer
execute as @a if score @s builder_used matches 3 run advancement grant @s only pvp_data:jobs/builder/3c_builder
execute as @a if score @s builder_used matches 20 run advancement grant @s only pvp_data:jobs/builder/20c_builder
execute as @a if score @s guardian_used matches 3 run advancement grant @s only pvp_data:jobs/guardian/3c_guardian
execute as @a if score @s guardian_used matches 20 run advancement grant @s only pvp_data:jobs/guardian/20c_guardian
execute as @a if score @s knight_used matches 3 run advancement grant @s only pvp_data:jobs/knight/3c_knight
execute as @a if score @s knight_used matches 20 run advancement grant @s only pvp_data:jobs/knight/20c_knight
execute as @a if score @s warrior_used matches 3 run advancement grant @s only pvp_data:jobs/warrior/3c_warrior
execute as @a if score @s warrior_used matches 20 run advancement grant @s only pvp_data:jobs/warrior/20c_warrior
execute as @a if score @s wizard_used matches 3 run advancement grant @s only pvp_data:jobs/wizard/3c_wizard
execute as @a if score @s wizard_used matches 20 run advancement grant @s only pvp_data:jobs/wizard/20c_wizard