scoreboard objectives add guardian_special_cool dummy
scoreboard objectives add guardian_special_con dummy
scoreboard players set $const guardian_special_con 20
scoreboard objectives add guardian_special_tp dummy